### ISSUE TITLE
Questions about adding a driver

### ISSUE THREAD

**Issue by Asten12** [LagradOst/Valox#1]
Can I add you on disc or something and ask some questions
i'm fairly new to cheats and I don't fully get the concept of using a driver to run cheats ud
Asten#7276 is my discord

**Comment by LagradOst** [comment]
a kernel driver is used to read/write mem because games are protected processes so you need a higher execution level than usermode aka kernelmode to touch another process memory.

might help: https://github.com/adspro15/km-um-communication

**Comment by Asten12** [comment]
> a kernel driver is used to read/write mem because games are protected processes so you need a higher execution level than usermode aka kernelmode to touch another process memory.
> 
> might help: https://github.com/adspro15/km-um-communication

so how could you integrate a driver into a cheat like when it needs to write memory it goes to the driver or something?
